In [1]:
import pandas as pd
import numpy as np

In [2]:
chan = pd.read_csv('clean_channels.csv')

In [4]:
chan['Hierarchy_Level'].unique()

array([1])

In [15]:
channel_volume_or = pd.read_csv('Untouched_Business_case/Data/Channel_Volume.csv', delimiter=',')

In [16]:
channel_volume_or

,Location,Industry,Edition,Category,Subcategory,Hierarchy_Level,Data_Type,Outlet,Outlet_Hierarchy,Unit,Year_text,Year_date,Volume
0,1,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2007,"Monday, 31 December 2007","2613,845506"
1,1,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2008,"Wednesday, 31 December 2008","2513,025824"
2,1,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2009,"Thursday, 31 December 2009","2421,088595"
3,1,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2010,"Friday, 31 December 2010","2422,128432"
4,1,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2011,"Saturday, 31 December 2011","2439,33622"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8463,7,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2017,"Sunday, 31 December 2017","16514,21084"
8464,7,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2018,"Monday, 31 December 2018","16522,15239"
8465,7,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2019,"Tuesday, 31 December 2019","16544,60644"
8466,7,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2020,"Thursday, 31 December 2020","16626,5149"
8467,7,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2021,"Friday, 31 December 2021","16664,638"

In [17]:
market_df = pd.read_csv('market_size_cleaned.csv')

In [18]:
market_df

,Unnamed: 0,Location,Industry,Subcategory,Hierarchy_Level,Data_Type,Unit,Current_Constant,Currency_Conversion,Year,Year_date,RSP (USD million),Volume (liters),Year_minus_2016,Year_minus_2022,Edition
0,0,1,Alcoholic Drinks,1,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2016,2016-12-31,301.000,27.000,4,-2,2022
1,1,1,Alcoholic Drinks,1,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2017,2017-12-31,318.000,28.000,5,-1,2022
2,2,1,Alcoholic Drinks,1,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2018,2018-12-31,458.000,40.000,6,0,2022
3,3,1,Alcoholic Drinks,1,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2019,2019-12-31,612.000,51.000,7,1,2022
4,4,1,Alcoholic Drinks,1,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2020,2020-12-31,774.000,62.000,8,2,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216,1216,7,Alcoholic Drinks,17,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2022,2022-12-31,6.545,1.204,10,4,2022
1217,1217,7,Alcoholic Drinks,17,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2023,2023-12-31,6.628,1.214,11,5,2022
1218,1218,7,Alcoholic Drinks,17,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2024,2024-12-31,6.708,1.227,12,6,2022
1219,1219,7,Alcoholic Drinks,17,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2025,2025-12-31,6.793,1.240,13,7,2022
1220,1220,7,Alcoholic Drinks,17,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2026,2026-12-31,6.892,1.256,14,8,2022

In [19]:
market_df['Year'].unique()

array([2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])